### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by morallo**
@Prof-Butts I have started moving stuff around and pushed to a WIP branch.

Still didn't fix all the imports, declarations etc. so it's not ready to merge, but if you can take a look to see if you are ok with the structure or you can suggest where to put things, I create this draft PR.

### TO FIX

- [x] Add globals declarations
- [x] Encoding issues (for example in Jérémy's name)

### TO DO

- [ ] classes

### CODE REVIEW

**Comment by Prof-Butts** [comment]
From what I can see, there are no functional changes here, only a (major) refactor. If that's the case, then this looks good to me.

Sorry for creating such a mess, and thank you for doing this much-needed refactor!

There was no way for you to know this, but some of that code is dead, and some SteamVR functions are also used in the DirectSBS path (so they should be in the common VR file). But those are minor details that can be fixed later. For this PR I think we should focus on the refactor without changing any functionality.

Looks like there are still a few things that need to be finalized in this PR, but once you're ready let me know and I'll merge it.

**Comment by morallo** [comment]
Thanks for the feedback.
If you see something misplaced, feel free to put a comment in the line itself with the code review features from GitHub!

Yesterday I split a lot more things, including DC, AC, bloom, materials, reticle...

Now I have a ton of compilation errors that I'm fixing slowly 😅
It's mostly putting the declarations of functions and globals in the right header files, and the corresponding includes.

I'll try to keep pushing my WIP.

**Comment by Prof-Butts** [comment]
Well, it doesn't have to be the full refactor in one go. We can do it in smaller steps too, making sure that master compiles and is stable at each step. For instance, the reticle code is particularly complicated, we can do that later.

BTW, I just noticed that some of the commits in your PR date back to July. I assume you refreshed your working copy from master recently -- just wanted to make sure.

Thanks again!

**Comment by morallo** [comment]
So, the refactor is in a buildable state, @Prof-Butts please check if it makes sense for you and if you want to merge now and start working with the new file organization.

There are still many things that should be taken away from Jeremy's class files, but it's a start.

**Pull request merged**
